name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
          - "3.7.13"
          - "3.8.12"
          - "3.9.12"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: '${{ matrix.python-version }}'
      - name: "Start MinIO"
        run: ./start-minio.sh
      - name: "Install package and python dependencies"
        run: |
          pip install .[dev]
          pip install https://github.com/rogerbinns/apsw/releases/download/3.36.0-r1/apsw-3.36.0-r1.zip --global-option=fetch --global-option=--version --global-option=3.36.0 --global-option=--sqlite --global-option=build --global-option=--enable-all-extensions
      - name: "Test"
        run: |
          pytest --cov
      - uses: codecov/codecov-action@v3
